runtime: custom
env: flex

entrypoint: gunicorn -b :$PORT fanaSystem.wsgi

env_variables:
    DJANGO_SETTINGS_MODULE: fanaSystem.settings

handlers:
- url: /static
  static_dir: staticfiles
- url: /.*
  script: auto

resources:
    cpu: 2
    memory_gb: 4


readiness_check:
  app_start_timeout_sec: 120
